### ISSUE TITLE
The objcxx symbols not found in libobjc2.

### ISSUE THREAD

**Issue by imkerberos** [crystax/android-samples-opengl#4] opened 2016-04-16 03:32 UTC
I have build use crystax-ndk-10.3.1 on Mac OS X.

> `
> [armeabi-v7a] SharedLibrary  : libapp-native.so
> /usr/local/Cellar/crystax-ndk/10.3.1/toolchains/llvm-3.7/prebuilt/darwin-x86_64/bin/clang++ -Wl,-soname,libapp-native.so -shared --sysroot=/usr/local/Cellar/crystax-ndk/10.3.1/platforms/android-9/arch-arm ./obj/local/armeabi-v7a/objs/app-native/engine.o ./obj/local/armeabi-v7a/objs/app-native/main.o ./obj/local/armeabi-v7a/objs/app-native/platform.o ./obj/local/armeabi-v7a/objs/app-native/__/__/common/AppController.o ./obj/local/armeabi-v7a/libandroid_native_app_glue.a ./obj/local/armeabi-v7a/liblegacy.a -lgcc ./obj/local/armeabi-v7a/libgnustl_shared.so ./obj/local/armeabi-v7a/libFoundation.so ./obj/local/armeabi-v7a/libCoreVideo.so ./obj/local/armeabi-v7a/libCoreText.so ./obj/local/armeabi-v7a/libCoreData.so ./obj/local/armeabi-v7a/libCoreGraphics.so ./obj/local/armeabi-v7a/libCoreFoundation.so ./obj/local/armeabi-v7a/libCFNetwork.so ./obj/local/armeabi-v7a/libCoreServices.so ./obj/local/armeabi-v7a/libobjc.so  -gcc-toolchain /usr/local/Cellar/crystax-ndk/10.3.1/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64 -no-canonical-prefixes -target armv7-none-linux-androideabi -Wl,--fix-cortex-a8  -Wl,--no-undefined -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -mthumb -fobjc-arc  -L/usr/local/Cellar/crystax-ndk/10.3.1/platforms/android-9/arch-arm/usr/lib -llog -landroid -lEGL -lGLESv2 -llog /usr/local/Cellar/crystax-ndk/10.3.1/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/libsupc++.a -llog -lGLESv2 -llog -lGLESv2 -llog -lGLESv2 -llog -lGLESv2 -llog -lGLESv2 -llog -lGLESv2 -llog -lGLESv2 -llog -lGLESv2 -L/usr/local/Cellar/crystax-ndk/10.3.1/sources/crystax/empty /usr/local/Cellar/crystax-ndk/10.3.1/sources/crystax/libs/armeabi-v7a/thumb/libcrystax.so -lc -o ./obj/local/armeabi-v7a/libapp-native.so
> ./obj/local/armeabi-v7a/objs/app-native/engine.o(.ARM.extab.text._i_Engine__initWithAndroidApp_+0x0): error: undefined reference to '__gnustep_objcxx_personality_v0'
> ./obj/local/armeabi-v7a/objs/app-native/engine.o(.ARM.extab.text._i_Engine__dealloc+0x0): error: undefined reference to '__gnustep_objcxx_personality_v0'
> ./obj/local/armeabi-v7a/objs/app-native/engine.o(.ARM.extab.text._i_Engine__setupGL+0x0): error: undefined reference to '__gnustep_objcxx_personality_v0'
> ./obj/local/armeabi-v7a/objs/app-native/engine.o(.ARM.extab.text._i_Engine__tearDownGL+0x0): error: undefined reference to '__gnustep_objcxx_personality_v0'
> clang++: error: linker command failed with exit code 1 (use -v to see invocation)
> make[1]: *** [obj/local/armeabi-v7a/libapp-native.so] Error 1
> `

**Comment by dmsck** [comment] 2016-04-17 10:08
This is duplicate of issue #2. Please read it and follow instructions there to solve it.

**Closed as completed by dmsck** 2016-04-17 10:08 UTC
